// Generated by gencpp from file rr_platform/speed.msg
// DO NOT EDIT!


#ifndef RR_PLATFORM_MESSAGE_SPEED_H
#define RR_PLATFORM_MESSAGE_SPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rr_platform
{
template <class ContainerAllocator>
struct speed_
{
  typedef speed_<ContainerAllocator> Type;

  speed_()
    : header()
    , speed(0.0)  {
    }
  speed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _speed_type;
  _speed_type speed;




  typedef boost::shared_ptr< ::rr_platform::speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rr_platform::speed_<ContainerAllocator> const> ConstPtr;

}; // struct speed_

typedef ::rr_platform::speed_<std::allocator<void> > speed;

typedef boost::shared_ptr< ::rr_platform::speed > speedPtr;
typedef boost::shared_ptr< ::rr_platform::speed const> speedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rr_platform::speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rr_platform::speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rr_platform

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'rr_platform': ['/home/brian/catkin_ws/src/roboracing-software/rr_platform/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rr_platform::speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rr_platform::speed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rr_platform::speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rr_platform::speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rr_platform::speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rr_platform::speed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rr_platform::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17b1dfb61067b5181d2fbfcebd547b10";
  }

  static const char* value(const ::rr_platform::speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17b1dfb61067b518ULL;
  static const uint64_t static_value2 = 0x1d2fbfcebd547b10ULL;
};

template<class ContainerAllocator>
struct DataType< ::rr_platform::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rr_platform/speed";
  }

  static const char* value(const ::rr_platform::speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rr_platform::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message for controlling the RC car servo and motors\n\
Header header           # timestamp in the header is the time the command is sent\n\
float64 speed             # wheel speed\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::rr_platform::speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rr_platform::speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rr_platform::speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rr_platform::speed_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RR_PLATFORM_MESSAGE_SPEED_H
