<robot name="rigatoni" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="use_gpu" value="false"/>

    <xacro:property name="props" value="${load_yaml('../conf/evgp_car_params.yaml')}"/>
    <xacro:property name="body_inertia" value="${props['body_inertia']}"/>

    <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>

    <!-- ************************** Links *************************** -->
    <xacro:macro name="null_inertia">
        <inertial>
            <mass value="0.0001"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="mesh_geometry">
        <geometry>
            <mesh filename="package://rr_description/meshes/rigatoni.stl" scale="0.01 0.01 0.01"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="set_link_color" params="link color">
        <gazebo reference="${link}">
            <material>Gazebo/${color}</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="evgp_body" params="collision_bitmask color">

        <!-- ************************** Links *************************** -->

        <link name="base_footprint">
            <xacro:null_inertia/>
        </link>

        <link name="body_visual_origin">
            <xacro:null_inertia/>
            <visual>
                <xacro:mesh_geometry/>
            </visual>
<!--            <collision>-->
<!--                <xacro:mesh_geometry/>-->
<!--            </collision>-->
        </link>
        <xacro:set_link_color link="body_visual_origin" color="${color}"/>
        <gazebo reference="body_visual_origin">
            <collision>
                <surface>
                    <contact>
                        <collide_bitmask>${collision_bitmask}</collide_bitmask>
                    </contact>
                </surface>
            </collision>
        </gazebo>

        <link name="body_inertial_center">
            <inertial>
                <mass value="${props['body_mass']}"/>
                <inertia ixx="${body_inertia[0]}" ixy="${body_inertia[1]}" ixz="${body_inertia[2]}"
                         iyy="${body_inertia[3]}" iyz="${body_inertia[4]}" izz="${body_inertia[5]}"/>
            </inertial>
        </link>
        <gazebo reference="body_inertial_center"/>


        <!-- ************************** Joints *************************** -->

        <joint name="base_footprint_to_mesh_origin" type="fixed">
            <parent link="base_footprint"/>
            <child link="body_visual_origin"/>
            <origin xyz="0.53 0 -0.05" rpy="${pi/2} 0 ${pi/2}"/>
        </joint>

        <joint name="base_footprint_to_body_inertial_center" type="fixed">
            <parent link="base_footprint"/>
            <child link="body_inertial_center"/>
            <origin xyz="${' '.join(str(x) for x in props['body_com'])}"/>
        </joint>

    </xacro:macro>
    <xacro:evgp_body collision_bitmask="0x1" color="Grey"/>

    <xacro:macro name="wheel_link" params="name radius width">
        <link name="${name}">
            <inertial>
                <mass value="0.01"/>
                <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0"
                         izz="${0.5 * props['wheel_mass'] * pow(radius, 2)}"/>
            </inertial>
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="${width}"/>
                </geometry>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${radius}" length="${width}"/>
                </geometry>
            </collision>
        </link>
        <gazebo reference="${name}">
            <mu1>0.7</mu1>
            <mu2>0.7</mu2>
            <kp>1000000</kp>
            <kd>1000000</kd>
            <collision>
                <surface>
                    <contact>
                        <collide_bitmask>0x1</collide_bitmask>
                    </contact>
                </surface>
            </collision>
        </gazebo>
        <xacro:set_link_color link="${name}" color="Black"/>
    </xacro:macro>
    <xacro:wheel_link name="wheel_BL" radius="${props['wheel_radius_back']}" width="${props['wheel_width_back']}"/>
    <xacro:wheel_link name="wheel_BR" radius="${props['wheel_radius_back']}" width="${props['wheel_width_back']}"/>
    <xacro:wheel_link name="wheel_FL" radius="${props['wheel_radius_front']}" width="${props['wheel_width_front']}"/>
    <xacro:wheel_link name="wheel_FR" radius="${props['wheel_radius_front']}" width="${props['wheel_width_front']}"/>

    <link name="steering_link_left">
        <xacro:null_inertia/>
    </link>
    <link name="steering_link_right">
        <xacro:null_inertia/>
    </link>

    <link name="gps_link">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </visual>
    </link>
    <xacro:set_link_color link="gps_link" color="Gold"/>

    <link name="camera">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </visual>
        <visual>
            <origin rpy="0 ${pi/2} 0" xyz="0.05 0 0"/>
            <geometry>
                <cylinder radius="0.03" length="0.05"/>
            </geometry>
        </visual>
    </link>
    <xacro:set_link_color link="camera" color="Gold"/>

    <link name="imu_top_link">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </visual>
    </link>
    <xacro:set_link_color link="imu_top_link" color="Gold"/>
    <link name="imu_bottom_link">
        <xacro:null_inertia/>
        <visual>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </visual>
    </link>
    <xacro:set_link_color link="imu_bottom_link" color="Gold"/>

    <xacro:macro name="april_link" params="name tag_number">
        <link name="${name}">
            <xacro:null_inertia/>
            <visual>
                <geometry>
                    <box size="0.001 0.127 0.127 "/>
                </geometry>
            </visual>
        </link>

        <gazebo reference="${name}">
            <material>${tag_number}</material>
        </gazebo>
    </xacro:macro>
    <xacro:april_link name="april_0" tag_number="tag36_11_00052"/>
    <xacro:april_link name="april_1" tag_number="tag36_11_00053"/>
    <xacro:april_link name="april_2" tag_number="tag36_11_00054"/>
    <xacro:april_link name="april_3" tag_number="tag36_11_00055"/>
    <xacro:april_link name="april_4" tag_number="tag36_11_00056"/>


    <!-- ************************** Joints *************************** -->

    <xacro:property name="joint_flop_both" value="0.03"/>
    <xacro:macro name="back_wheel_joint" params="dest_link y">
        <joint name="base_footprint_to_${dest_link}" type="continuous">
            <parent link="base_footprint"/>
            <child link="${dest_link}"/>
            <origin xyz="0 ${y} ${(props['wheel_radius_back'] / 2) - joint_flop_both}" rpy="${-pi/2} 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>
        <gazebo reference="base_footprint_to_${dest_link}"/>
    </xacro:macro>
    <xacro:back_wheel_joint dest_link="wheel_BL" y="${props['track'] / 2}"/>
    <xacro:back_wheel_joint dest_link="wheel_BR" y="${-props['track'] / 2}"/>

    <xacro:property name="joint_flop_front" value="0.007"/>
    <xacro:macro name="steering_joints" params="steering_link wheel_link y">
        <joint name="base_footprint_to_${steering_link}" type="revolute">
            <parent link="base_footprint"/>
            <child link="${steering_link}"/>
            <origin xyz="${props['wheelbase']} ${y} ${props['wheel_radius_front'] / 2}" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
            <limit lower="${-props['max_steering']}" upper="${props['max_steering']}" effort="10000.0"
                   velocity="${props['steering_speed']}"/>
        </joint>
        <gazebo reference="base_footprint_to_${steering_link}"/>

        <joint name="${steering_link}_to_${wheel_link}" type="continuous">
            <origin xyz="0 0 ${-joint_flop_both - joint_flop_front}" rpy="${pi/2} 0 0"/>
            <parent link="${steering_link}"/>
            <child link="${wheel_link}"/>
            <axis xyz="0 0 1"/>
        </joint>
        <gazebo reference="${steering_link}_to_${wheel_link}"/>
    </xacro:macro>
    <xacro:steering_joints steering_link="steering_link_left" wheel_link="wheel_FL" y="${props['track'] / 2}"/>
    <xacro:steering_joints steering_link="steering_link_right" wheel_link="wheel_FR" y="${-props['track'] / 2}"/>

    <xacro:macro name="camera_optical_frame" params="camera_link">
        <link name="${camera_link}_optical">
            <xacro:null_inertia/>
        </link>
        <joint name="${camera_link}_to_optical" type="fixed">
            <parent link="${camera_link}"/>
            <child link="${camera_link}_optical"/>
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
        </joint>
    </xacro:macro>

    <xacro:camera_optical_frame camera_link="camera"/>

    <xacro:macro name="set_base_footprint_to_link" params="link_name xyz rpy">
        <joint name="base_footprint_to_${link_name}" type="fixed">
            <parent link="base_footprint"/>
            <child link="${link_name}"/>
            <origin xyz="${xyz}" rpy="${rpy}"/>
        </joint>
    </xacro:macro>

    <xacro:set_base_footprint_to_link link_name="gps_link" xyz="0.55 0.39 1.22" rpy="0 0 0"/>

    <xacro:set_base_footprint_to_link link_name="camera" xyz="0.61 0.39 1.03" rpy="0 0.4 0"/>

    <xacro:set_base_footprint_to_link link_name="imu_bottom_link" xyz="0 0 0.21" rpy="0 0 0"/>
    <xacro:set_base_footprint_to_link link_name="imu_top_link" xyz="0.60 0.39 0.95" rpy="0 0 0"/>

    <xacro:set_base_footprint_to_link link_name="april_0" xyz=".48  -0.55 0.26" rpy="0 0 ${pi/2}"/>
    <xacro:set_base_footprint_to_link link_name="april_1" xyz="-.19 -0.43 0.26" rpy="0 0 ${pi/4}"/>
    <xacro:set_base_footprint_to_link link_name="april_2" xyz="-.38  0    0.26" rpy="0 0 0"/>
    <xacro:set_base_footprint_to_link link_name="april_3" xyz="-.19  0.43 0.26" rpy="0 0 -${pi/4}"/>
    <xacro:set_base_footprint_to_link link_name="april_4" xyz=".48   0.55 0.26" rpy="0 0 ${pi/2}"/>


    <!-- ******************* Sensors *********************** -->

    <!-- Velodyne Puck VLP-16 -->
    <xacro:VLP-16 parent="base_footprint" name="lidar" topic="/velodyne_points" hz="10" samples="500" gpu="true">
        <origin xyz="1.175 0 0.175" rpy="0 0 0" />
    </xacro:VLP-16>

    <!-- FLIR Blackfly + wide-angle lens -->
    <gazebo reference="camera">
        <sensor name="camera_sensor" type="camera">
            <camera>
                <horizontal_fov>1.6955</horizontal_fov>
                <image>
                    <width>1280</width>
                    <height>964</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>100</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
            </camera>
            <always_on>true</always_on>
            <update_rate>15</update_rate>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <alwaysOn>true</alwaysOn>
                <cameraName>camera</cameraName>
                <imageTopicName>image_color_rect</imageTopicName>
                <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                <frameName>camera_optical</frameName>
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
            </plugin>
        </sensor>
    </gazebo>

    <!-- IMU -->
    <gazebo reference="imu_top_link">
        <gravity>true</gravity>
        <sensor name="imu_sensor" type="imu">
            <always_on>true</always_on>
            <update_rate>100</update_rate>
            <visualize>true</visualize>
            <topic>__default_topic__</topic>
            <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
                <topicName>imu</topicName>
                <bodyName>imu_top_link</bodyName>
                <updateRateHZ>20.0</updateRateHZ>
                <gaussianNoise>0.005</gaussianNoise>
                <xyzOffset>0 0 0</xyzOffset>
                <rpyOffset>0 0 0</rpyOffset>
                <frameName>imu_top_link</frameName>
            </plugin>
            <pose>0 0 0 0 0 0</pose>
        </sensor>
    </gazebo>

    <!-- IMU -->
    <gazebo reference="imu_bottom_link">
        <gravity>true</gravity>
        <sensor name="imu_sensor_bottom" type="imu">
            <always_on>true</always_on>
            <update_rate>100</update_rate>
            <visualize>true</visualize>
            <topic>__default_topic__</topic>
            <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
                <topicName>imu</topicName>
                <bodyName>imu_bottom_link</bodyName>
                <updateRateHZ>20.0</updateRateHZ>
                <gaussianNoise>0.005</gaussianNoise>
                <xyzOffset>0 0 0</xyzOffset>
                <rpyOffset>0 0 0</rpyOffset>
                <frameName>imu_bottom_link</frameName>
            </plugin>
            <pose>0 0 0 0 0 0</pose>
        </sensor>
    </gazebo>

    <!-- GPS -->
    <gazebo>
        <plugin name="gps_controller" filename="libhector_gazebo_ros_gps.so">
            <robotNamespace>/</robotNamespace>
            <updateRate>10</updateRate>
            <bodyName>gps_link</bodyName>
            <frameId>gps_link</frameId>
            <topicName>gps/fix</topicName>
            <velocityTopicName>gps/vel</velocityTopicName>
            <referenceLatitude>33.8</referenceLatitude>
            <referenceLongitude>-84.4</referenceLongitude>
            <referenceHeading>0</referenceHeading>
            <referenceAltitude>0</referenceAltitude>
            <drift>0.2 0.2 0.2</drift>
            <driftFrequency>0.01 0.01 0.01</driftFrequency>
            <gaussianNoise>0.05 0.05 0.05</gaussianNoise>
            <velocityDrift>0.05 0.05 0.05</velocityDrift>
            <velocityDriftFrequency>0.1 0.1 0.1</velocityDriftFrequency>
            <velocityGaussianNoise>0.05 0.05 0.05</velocityGaussianNoise>
        </plugin>
    </gazebo>

    <!-- ground-truth localization plugin -->
    <gazebo>
        <plugin name="ground_truth_tracker" filename="libgazebo_ros_p3d.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>10.0</updateRate>
            <bodyName>base_footprint</bodyName>
            <topicName>/odometry/ground_truth</topicName>
            <gaussianNoise>0.0</gaussianNoise>
            <frameName>world</frameName>
            <xyzOffsets>0 0 0</xyzOffsets>
            <rpyOffsets>0 0 0</rpyOffsets>
        </plugin>
    </gazebo>


    <!-- ****************** Actuators ********************** -->

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/</robotNamespace>
        </plugin>
    </gazebo>

    <transmission name="trans_back_left">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="base_footprint_to_wheel_BL">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_left">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="trans_back_right">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="base_footprint_to_wheel_BR">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_right">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="left_steering_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="base_footprint_to_steering_link_left">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="left_steer_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="right_steering_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="base_footprint_to_steering_link_right">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="right_steer_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

</robot>
