// Generated by gencpp from file avc/calibrate_imageResponse.msg
// DO NOT EDIT!


#ifndef AVC_MESSAGE_CALIBRATE_IMAGERESPONSE_H
#define AVC_MESSAGE_CALIBRATE_IMAGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace avc
{
template <class ContainerAllocator>
struct calibrate_imageResponse_
{
  typedef calibrate_imageResponse_<ContainerAllocator> Type;

  calibrate_imageResponse_()
    : x(false)  {
    }
  calibrate_imageResponse_(const ContainerAllocator& _alloc)
    : x(false)  {
  (void)_alloc;
    }



   typedef uint8_t _x_type;
  _x_type x;




  typedef boost::shared_ptr< ::avc::calibrate_imageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avc::calibrate_imageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct calibrate_imageResponse_

typedef ::avc::calibrate_imageResponse_<std::allocator<void> > calibrate_imageResponse;

typedef boost::shared_ptr< ::avc::calibrate_imageResponse > calibrate_imageResponsePtr;
typedef boost::shared_ptr< ::avc::calibrate_imageResponse const> calibrate_imageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avc::calibrate_imageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avc::calibrate_imageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace avc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::avc::calibrate_imageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avc::calibrate_imageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avc::calibrate_imageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avc::calibrate_imageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avc::calibrate_imageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avc::calibrate_imageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avc::calibrate_imageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e7c7f7c11db7cc314e9efb95e17c2ed";
  }

  static const char* value(const ::avc::calibrate_imageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e7c7f7c11db7cc3ULL;
  static const uint64_t static_value2 = 0x14e9efb95e17c2edULL;
};

template<class ContainerAllocator>
struct DataType< ::avc::calibrate_imageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avc/calibrate_imageResponse";
  }

  static const char* value(const ::avc::calibrate_imageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avc::calibrate_imageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool x\n\
";
  }

  static const char* value(const ::avc::calibrate_imageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avc::calibrate_imageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct calibrate_imageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avc::calibrate_imageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avc::calibrate_imageResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVC_MESSAGE_CALIBRATE_IMAGERESPONSE_H
