// Generated by gencpp from file avc/calibrate_imageRequest.msg
// DO NOT EDIT!


#ifndef AVC_MESSAGE_CALIBRATE_IMAGEREQUEST_H
#define AVC_MESSAGE_CALIBRATE_IMAGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace avc
{
template <class ContainerAllocator>
struct calibrate_imageRequest_
{
  typedef calibrate_imageRequest_<ContainerAllocator> Type;

  calibrate_imageRequest_()
    : image()
    , imgDim()
    , pixelsPerMeter(0.0)
    , distanceToChessboard(0.0)
    , chessboardDim()
    , squareWidth(0.0)  {
      imgDim.assign(0);

      chessboardDim.assign(0);
  }
  calibrate_imageRequest_(const ContainerAllocator& _alloc)
    : image(_alloc)
    , imgDim()
    , pixelsPerMeter(0.0)
    , distanceToChessboard(0.0)
    , chessboardDim()
    , squareWidth(0.0)  {
  (void)_alloc;
      imgDim.assign(0);

      chessboardDim.assign(0);
  }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;

   typedef boost::array<int64_t, 2>  _imgDim_type;
  _imgDim_type imgDim;

   typedef double _pixelsPerMeter_type;
  _pixelsPerMeter_type pixelsPerMeter;

   typedef double _distanceToChessboard_type;
  _distanceToChessboard_type distanceToChessboard;

   typedef boost::array<int64_t, 2>  _chessboardDim_type;
  _chessboardDim_type chessboardDim;

   typedef double _squareWidth_type;
  _squareWidth_type squareWidth;




  typedef boost::shared_ptr< ::avc::calibrate_imageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avc::calibrate_imageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct calibrate_imageRequest_

typedef ::avc::calibrate_imageRequest_<std::allocator<void> > calibrate_imageRequest;

typedef boost::shared_ptr< ::avc::calibrate_imageRequest > calibrate_imageRequestPtr;
typedef boost::shared_ptr< ::avc::calibrate_imageRequest const> calibrate_imageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avc::calibrate_imageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avc::calibrate_imageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace avc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::avc::calibrate_imageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avc::calibrate_imageRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avc::calibrate_imageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avc::calibrate_imageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avc::calibrate_imageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avc::calibrate_imageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avc::calibrate_imageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7709420ba6eef1457180f15a14042fc";
  }

  static const char* value(const ::avc::calibrate_imageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7709420ba6eef14ULL;
  static const uint64_t static_value2 = 0x57180f15a14042fcULL;
};

template<class ContainerAllocator>
struct DataType< ::avc::calibrate_imageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avc/calibrate_imageRequest";
  }

  static const char* value(const ::avc::calibrate_imageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avc::calibrate_imageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image image\n\
int64[2] imgDim\n\
float64 pixelsPerMeter\n\
float64 distanceToChessboard\n\
int64[2] chessboardDim\n\
float64 squareWidth\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::avc::calibrate_imageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avc::calibrate_imageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image);
      stream.next(m.imgDim);
      stream.next(m.pixelsPerMeter);
      stream.next(m.distanceToChessboard);
      stream.next(m.chessboardDim);
      stream.next(m.squareWidth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct calibrate_imageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avc::calibrate_imageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avc::calibrate_imageRequest_<ContainerAllocator>& v)
  {
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
    s << indent << "imgDim[]" << std::endl;
    for (size_t i = 0; i < v.imgDim.size(); ++i)
    {
      s << indent << "  imgDim[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.imgDim[i]);
    }
    s << indent << "pixelsPerMeter: ";
    Printer<double>::stream(s, indent + "  ", v.pixelsPerMeter);
    s << indent << "distanceToChessboard: ";
    Printer<double>::stream(s, indent + "  ", v.distanceToChessboard);
    s << indent << "chessboardDim[]" << std::endl;
    for (size_t i = 0; i < v.chessboardDim.size(); ++i)
    {
      s << indent << "  chessboardDim[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.chessboardDim[i]);
    }
    s << indent << "squareWidth: ";
    Printer<double>::stream(s, indent + "  ", v.squareWidth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVC_MESSAGE_CALIBRATE_IMAGEREQUEST_H
