#request
sensor_msgs/Image image

float64 mapPixelsPerMeter

#number of rows of squares on the board
#conversion to interior vertices done automatically
int64 chessboardRows

#number of columns
int64 chessboardCols

#meters
float64 squareWidth

---

#response: indication of whether the chessboard was identified
bool x
