(cl:defpackage avc-srv
  (:use )
  (:export
   "CALIBRATE_IMAGE"
   "<CALIBRATE_IMAGE-REQUEST>"
   "CALIBRATE_IMAGE-REQUEST"
   "<CALIBRATE_IMAGE-RESPONSE>"
   "CALIBRATE_IMAGE-RESPONSE"
   "TRANSFORM_IMAGE"
   "<TRANSFORM_IMAGE-REQUEST>"
   "TRANSFORM_IMAGE-REQUEST"
   "<TRANSFORM_IMAGE-RESPONSE>"
   "TRANSFORM_IMAGE-RESPONSE"
  ))

